### ISSUE TITLE
Issue with the String split transform

### ISSUE THREAD

**Issue by VVincent0** [lithnet/umare#2] opened 2017-06-13 11:04 UTC
Hello, i tried to use the String split transform method in the Lithnet UMARE Editor.

I used the example : 
Regular expression split ","
Input Value 1 "Value1,Value2"

I expect : 
Transform output "Value1" and "Value2" in seperate ligne (multivalued output)

But here is what i have : 
V
a
l
u
e
1
,
V
a
l
u
e
2

Can you tell me if i do something wrong or is it a really bug ?

Screenshot in attachement .

Regards
![sc](https://user-images.githubusercontent.com/29401383/27079669-db247c9e-5038-11e7-9761-1e5ab2de6183.PNG)

**Comment by ryannewington** [comment] 2017-06-13 11:07
That's very strange. I've just run it myself, and I get the expected behavior. Does it make a difference if you escape the comma in the regex pattern?
`\,`

**Comment by ryannewington** [comment] 2017-06-13 11:14
I did just find a UI bug. It seems that the first pattern you put in the regex text box stays loaded in memory, no matter what you change it to afterwards. Save the umare file, close the editor, reopen, and test again to see if its just because of this issue.

**Comment by VVincent0** [comment] 2017-06-13 11:24
That's allright, when i reload the editor i have the expected behavior.

Thank you

**Comment by ryannewington** [comment] 2017-06-13 11:26
I've raised a bug to fix the fault in the [transform engine](https://github.com/lithnet/transform-engine/issues/2), and i'll update this issue when I release the updated UMARE that includes this fix.

**Comment by ryannewington** [comment] 2017-06-13 11:38
Fixed in https://github.com/lithnet/umare/releases/tag/v1.5.6373

**Closed as completed by ryannewington** 2017-06-13 11:38 UTC
Labels: bug
